places_remember/urls.py
from django.urls import path

from places_remember import views

app_name = "places_remember"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("memories/new/", views.CreateMemoryView.as_view(), name="create_memory"),
    path("memories/<int:pk>/", views.UpdateMemoryView.as_view(), name="update_memory"),
    path("memories/<int:pk>/delete/", views.DeleteMemoryView.as_view(), name="delete_memory"),
]

places_remember_project/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import login

urlpatterns = [
    path("", include("places_remember.urls")),
    path("admin/", admin.site.urls),
    path("accounts/signup/", login, name="account_signup"),  # Forbid manual signup, users must use Facebook instead
    path("accounts/", include("allauth.urls")),
]

# TODO: add 404 and 403 custom handlers

places_remember/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _, gettext


class Memory(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name=_("user"))
    title = models.CharField(max_length=100, verbose_name=_("title"))
    text = models.TextField(max_length=1000, verbose_name=_("text"))

    class Meta:
        verbose_name = _("memory")
        verbose_name_plural = _("memories")
        indexes = [
            models.Index(fields=("user_id",))
        ]

    def __str__(self):
        if self.user.first_name or self.user.last_name:
            username = f"{self.user.first_name} {self.user.last_name}"
        else:
            username = self.user.username
        # return f"{username}'s memory about {self.place}: {self.title}"
        return gettext("%(username)s's memory about %(place)s: %(title)s") % {
            "username": username,
            "place": self.place,
            "title": self.title
        }

    def get_absolute_url(self):
        return reverse("places_remember:update_memory", kwargs={"pk": self.pk})


class Place(models.Model):
    latitude = models.FloatField(verbose_name=_("latitude"))
    longitude = models.FloatField(verbose_name=_("longitude"))
    zoom = models.IntegerField(verbose_name=_("zoom"))
    place_id = models.IntegerField(null=True, blank=True, verbose_name=_("place id"))
    place_name = models.CharField(max_length=100, blank=True, verbose_name=_("place name"))
    memory = models.OneToOneField(Memory, on_delete=models.CASCADE, verbose_name=_("memory"))
    
    class Meta:
        verbose_name = _("place")
        verbose_name_plural = _("places")

    def __str__(self):
        place_name = self.place_name if self.place_name else gettext("Unknown place")
        return gettext("%(place_name)s at %(latitude)f,%(longitude)f") % {
            "place_name": place_name,
            "latitude": self.latitude,
            "longitude": self.longitude
        }

    @property
    def ymap_url(self):
        return f"https://static-maps.yandex.ru/1.x/?l=map&ll={self.longitude},{self.latitude}&size=600,400&z={self.zoom}&pt={self.longitude},{self.latitude},pm2dom"

places_remember/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class MemoryForm(forms.Form):
    latitude = forms.FloatField(widget=forms.HiddenInput())
    longitude = forms.FloatField(widget=forms.HiddenInput())
    zoom = forms.FloatField(widget=forms.HiddenInput())
    place_id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    place_name = forms.CharField(max_length=100, required=False, widget=forms.HiddenInput())
    title = forms.CharField(label=_("Title"), max_length=100)
    text = forms.CharField(label=_("Text"), widget=forms.Textarea, max_length=1000)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs["class"] = "form-control"
        self.fields["text"].widget.attrs["class"] = "form-control"
        label_suffix = kwargs.get("label_suffix", None)
        self.label_suffix = label_suffix if label_suffix is not None else ""

    def clean_latitude(self):
        latitude = self.cleaned_data["latitude"]
        if -90 <= latitude <= 90:
            return latitude
        else:
            raise ValidationError(_("Latitude must be in a range from -90 to 90"), code="invalid")

    def clean_longitude(self):
        longitude = self.cleaned_data["longitude"]
        if -180 <= longitude <= 180:
            return longitude
        else:
            raise ValidationError(_("Longitude must be in a range from -180 to 180"), code="invalid")

    def clean_zoom(self):
        zoom = self.cleaned_data["zoom"]
        if 0 <= zoom <= 21:
            # Usual Yandex maps can produce float zoom on devices with touchscreen.
            # Though api documentation defines it as integer and static maps does not support float zoom.
            return int(zoom)
        else:
            raise ValidationError(_("Zoom must be in a range from 0 (entire world) to 21"))

places_remember/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction, IntegrityError
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import FormView, DeleteView
from django.utils.translation import gettext_lazy as _
from places_remember import forms, models


class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            current_user_memories = models.Memory.objects.filter(user=self.request.user)
            context = {
                "memory_list": current_user_memories
            }
            return TemplateResponse(request, "places_remember/index_authenticated.html", context)
        else:
            return TemplateResponse(request, "places_remember/index_not_authenticated.html")


class AboutView(View):
    def get(self, request):
        return TemplateResponse(request, "places_remember/about.html")


@method_decorator(login_required, name="dispatch")
class CreateMemoryView(FormView):
    template_name = "places_remember/memory_form.html"
    form_class = forms.MemoryForm
    success_url = reverse_lazy("places_remember:index")
    initial = {
        "latitude": 56.83800773134774,
        "longitude": 60.60362527445821,
        "zoom": 16,
    }
    extra_context = {
        "title": _("Add memory")
    }

    def form_valid(self, form):
        try:
            with transaction.atomic():
                memory = models.Memory.objects.create(
                    user=self.request.user,
                    title=form.cleaned_data["title"],
                    text=form.cleaned_data["text"]
                )
                place = models.Place.objects.create(
                    latitude=form.cleaned_data["latitude"],
                    longitude=form.cleaned_data["longitude"],
                    zoom=form.cleaned_data["zoom"],
                    place_id=form.cleaned_data["place_id"],
                    place_name=form.cleaned_data["place_name"],
                    memory=memory
                )
        except IntegrityError as error:
            log = logging.getLogger(__name__)
            log.exception(
                "Memory creation caused IntegrityError while being called with following form's cleaned data: %s",
                form.cleaned_data
            )
            raise
        else:
            return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class UpdateMemoryView(UserPassesTestMixin, FormView):
    template_name = "places_remember/memory_form.html"
    form_class = forms.MemoryForm
    success_url = reverse_lazy("places_remember:index")
    extra_context = {
        "title": _("Edit memory")
    }

    def test_func(self):
        pk = self.kwargs["pk"]
        memory = get_object_or_404(models.Memory, pk=pk)
        return memory.user == self.request.user

    def get_initial(self):
        pk = self.kwargs["pk"]
        memory = get_object_or_404(models.Memory, pk=pk)
        place = memory.place
        initial = super().get_initial()
        initial.update({
            "latitude": place.latitude,
            "longitude": place.longitude,
            "zoom": place.zoom,
            "place_id": place.place_id,
            "place_name": place.place_name,
            "title": memory.title,
            "text": memory.text
        })
        return initial

    def form_valid(self, form):
        pk = self.kwargs["pk"]
        try:
            with transaction.atomic():
                memory = get_object_or_404(models.Memory, pk=pk)
                memory.title = form.cleaned_data["title"]
                memory.text = form.cleaned_data["text"]
                memory.save()
                memory.place.latitude = form.cleaned_data["latitude"]
                memory.place.longitude = form.cleaned_data["longitude"]
                memory.place.zoom = form.cleaned_data["zoom"]
                memory.place.place_id = form.cleaned_data["place_id"]
                memory.place.place_name = form.cleaned_data["place_name"]
                memory.place.save()
        except IntegrityError as error:
            log = logging.getLogger(__name__)
            log.exception(
                "Memory update caused IntegrityError while being called with following form's cleaned data: %s",
                form.cleaned_data
            )
        else:
            return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class DeleteMemoryView(UserPassesTestMixin, DeleteView):
    success_url = reverse_lazy("places_remember:index")

    def test_func(self):
        memory = self.get_object()
        return memory.user == self.request.user

    def get_queryset(self):
        current_user_memories = models.Memory.objects.filter(user=self.request.user)
        return current_user_memories

places_remember/templates/places_remember/about.html
{% extends 'places_remember/base.html' %}
{% load i18n %}

{% block content %}
<div class="container">
    <address class="mt-3">
        <p>
            {% translate 'Developed by' %} Dmitry Smirnov<br/>
            <a class="" href="mailto:sda97g@gmail.com">sda97g@gmail.com</a><br/>
            <a href="https://github.com/sda97ghb/interesnee_places_remember">GitHub</a>
        </p>
    </address>
</div>
{% endblock content%}

places_remember/templates/places_remember/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}Places remember{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'places_remember/css/base.css' %}">
    {% block head_extra %}
    {% endblock head_extra %}
</head>
<body>

<header class="container-xl px-0">
    {% block header %}
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'places_remember:index' %}">Places remember</a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'places_remember:index' %}">{% translate 'Home' %}</a>
                </li>
                {% if user.is_authenticated %}
                <li class="navbar-nav">
                    <a class="nav-link" href="{% url 'places_remember:create_memory' %}">{% translate 'Add memory' %}</a>
                </li>
                {% endif %}
                <li class="navbar-nav">
                    <a class="nav-link" href="{% url 'places_remember:about' %}">{% translate 'About' %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">{{ user.username }}</span>
                </li>
                {% endif %}
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'account_logout' %}">{% translate 'Logout' %}</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'account_login' %}">{% translate 'Login' %}</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {% endblock header %}
</header>

<main class="container-fluid px-0">
    {% block content %}
    {% endblock content %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
{% block scripts %}
{% endblock scripts %}

</body>
</html>

places_remember/templates/places_remember/index_authenticated.html
{% extends 'places_remember/base.html' %}
{% load static %}
{% load i18n %}
{% load socialaccount %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'places_remember/css/index_authenticated.css' %}">
{% endblock head_extra%}

{% block content %}
<section class="container mt-4">
    <div class="row">
        <div class="col-auto mx-auto">
            {% get_social_accounts user as accounts %}
            <img class="profile-picture rounded-circle border" src="{{ accounts.facebook.0.get_avatar_url }}"
                 alt="{% translate "User's photo" %}"/>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col text-center h4">
            {{ user.first_name }} {{ user.last_name }}
        </div>
    </div>
</section>
<div class="container mt-3 mb-4">
    <div class="row">
        <div class="col-auto mx-auto">
            <a class="btn btn-primary" role="button" href="{% url 'places_remember:create_memory' %}">
                {% translate 'Add memory' %}
            </a>
        </div>
    </div>
</div>
<section class="container">
    {% if memory_list %}
    <ul class="list-unstyled">
        {% for memory in memory_list %}
        <li class="media flex-column flex-md-row mb-3">
            <img class="map-preview mr-2 mb-2" src="{{ memory.place.ymap_url }}" alt="Memory place's map">
            <div class="media-body">
                <h4 class="text-break">
                    {{ memory.title }}
                </h4>
                <p class="text-black-50 mb-2">
                    {{ memory.place }}
                </p>
                <p class="mb-2 text-break">
                    {{ memory.text|truncatechars:200 }}
                </p>
                <div>
                    <a href="{% url 'places_remember:update_memory' pk=memory.pk %}">{% translate 'Edit' %}</a>
                    <a href="{% url 'places_remember:delete_memory' pk=memory.pk %}">{% translate 'Delete' %}</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="row align-items-center justify-content-center empty-state">
        <div class="col-auto text-center">
            {% translate 'There are no memories yet.' %}<br/>
            {% url 'places_remember:create_memory' as create_memory_url %}
            {% blocktranslate %}Let's <a href="{{ create_memory_url }}">add one</a>!{% endblocktranslate %}
        </div>
    </div>
    {% endif %}
</section>
{% endblock content%}

places_remember/templates/places_remember/index_not_authenticated.html
{% extends 'places_remember/base.html' %}
{% load static %}
{% load i18n %}
{% load socialaccount %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'places_remember/css/index_not_authenticated.css' %}">
{% endblock head_extra %}

{% block content %}
<div class="container d-block d-lg-none">
    <img class="w-100 mt-4 mb-3 border shadow-sm" src="{% static 'places_remember/img/preview/list_of_memories.png' %}"
         alt="Your personal list of memories">
    <h4>{% translate 'Your personal memories collection' %}</h4>
    <p>
        {% translate 'Point any place, write down your memories and save them in your personal collection.' %}
    </p>
    <p>
        {% translate 'Nothing will be forgotten!' %}
    </p>
    <img class="w-100 mt-3 mb-3 border shadow-sm" src="{% static 'places_remember/img/preview/memory_editing.png' %}"
         alt="Memory editing: choose location on a map and write your memory down">
    <h4>{% translate 'As accurate as you need' %}</h4>
    <p>
        {% translate 'City, street or random location far away?<br/>Choose <strong>any</strong> place!' %}
    </p>
    <p>
        {% translate 'Write text up to 1000 characters long!' %}
    </p>
    <div class="row my-5">
        <div class="col-auto mx-auto">
            {% translate 'Try it now with' %}
            <a class="btn btn-primary" href="{% provider_login_url 'facebook' method='oauth2' %}">{% translate 'Facebook login' %}</a>
            !
        </div>
    </div>
</div>
<div class="container-xl d-none d-lg-block">
    <div class="row align-items-center">
        <div class="col-5 offset-1">
            <img class="img-preview-big mt-4 mb-3 border shadow"
                 src="{% static 'places_remember/img/preview/list_of_memories.png' %}"
                 alt="Your personal list of memories">
        </div>
        <div class="col-5">
            <h4>{% translate 'Your personal memories collection' %}</h4>
            <p>
                {% translate 'Point any place, write down your memories and save them in your personal collection.' %}
            </p>
            <p>
                {% translate 'Nothing will be forgotten!' %}
            </p>
        </div>
    </div>
    <div class="row align-items-center">
        <div class="col-5 offset-1">
            <h4>{% translate 'As accurate as you need' %}</h4>
            <p>
                {% translate 'City, street or random location far away?<br/>Choose <strong>any</strong> place!' %}
            </p>
            <p>
                {% translate 'Write text up to 1000 characters long!' %}
            </p>
        </div>
        <div class="col-5">
            <img class="img-preview-big mt-3 mb-3 border shadow"
                 src="{% static 'places_remember/img/preview/memory_editing.png' %}"
                 alt="Memory editing: choose location on a map and write your memory down">
        </div>
    </div>
    <div class="row my-5">
        <div class="col-auto mx-auto">
            {% translate 'Try it now with' %}
            <a class="btn btn-primary" href="{% provider_login_url 'facebook' method='oauth2' %}">{% translate 'Facebook login' %}</a>
            !
        </div>
    </div>
</div>
{% endblock content%}

places_remember/templates/places_remember/memory_confirm_delete.html
{% extends 'places_remember/base.html' %}
{% load static %}
{% load i18n %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'places_remember/css/index_authenticated.css' %}">
{% endblock head_extra%}

{% block content %}
<form class="container" method="post">{% csrf_token %}
    <p class="mt-3">{% translate 'Are you sure you want to delete this memory?' %}</p>
    <div class="row border pt-3 pb-0 mx-0">
        <div class="col">
            <div class="media flex-column flex-md-row mb-3">
                <img class="map-preview mr-2" src="{{ memory.place.ymap_url }}"
                     alt="{% translate "Memory place's map" %}">
                <div class="media-body">
                    <h4 class="text-break">
                        {{ memory.title }}
                    </h4>
                    <p class="text-black-50 mb-2">
                        {{ memory.place }}
                    </p>
                    <p class="mb-2 text-break">
                        {{ memory.text|truncatechars:200 }}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <input class="btn btn-danger mt-3" type="submit" value="{% translate 'Confirm' %}">
</form>
{% endblock content%}

places_remember/templates/places_remember/memory_form.html
{% extends 'places_remember/base.html' %}
{% load static %}
{% load i18n %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'places_remember/css/memory_form.css' %}">
{% endblock head_extra%}

{% block content %}
<div class="container px-0">
    <h2 class="my-3">
        {% if title %}
        {{ title }}
        {% else %}
        {% translate 'Memory' %}
        {% endif %}
    </h2>

    <div id="map" class="bg-light w-100 map">
        <div class="map-marker-wrapper">
            <svg class="map-marker text-primary bi bi-geo-alt-fill" fill="currentColor" viewBox="0 0 16 16"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            </svg>
        </div>
    </div>

    <form class="my-3 mx-3 mx-md-0" method="post">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
        {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field.as_widget }}
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="{% translate 'Save' %}">
    </form>
</div>
{% endblock content%}

{% block scripts %}
{% autoescape off %}
{{ yandex_maps.api_script }}
{% endautoescape %}
<script src="{% static 'places_remember/js/memory_form.js' %}" type="text/javascript"></script>
{% endblock scripts %}